# NLP feature extraction for Bulgarian emotion recognition

Part-of-speech tagging, TF-IDF, sentiment, pretrained and custom word embeddings, and one extra feature, computed on the Bulgarian test-set sentences.

## Subtask 1: Part_of_speech (POS) tagging

In [ ]:
# Language Configuration - ONLY CHANGE THIS PARAMETER
LANGUAGE = 'bg'  # Change to 'en', 'de', 'fr', etc. for other languages

LANGUAGE_CONFIG = {
    'bg': {
        'spacy_model': 'bg_news_lg',
        'text_column': 'sentence_text_bg',
        'fasttext_model': 'cc.bg.300.bin',
        'corpus_file': 'bulgarian_corpus.txt',
        'sentiment_model': 'lxyuan/distilbert-base-multilingual-cased-sentiments-student'
    },
    'en': {
        'spacy_model': 'en_core_web_lg',
        'text_column': 'sentence_text',
        'fasttext_model': 'cc.en.300.bin',
        'corpus_file': 'english_corpus.txt',
        'sentiment_model': 'cardiffnlp/twitter-roberta-base-sentiment-latest'
    }
}

config = LANGUAGE_CONFIG[LANGUAGE]

In [1]:
import spacy
import pandas as pd
print(spacy.__version__)

3.5.4

In [2]:
import chardet

In [3]:
# Detect the encoding of the CSV file
with open("bg_final.csv", "rb") as file:
    result = chardet.detect(file.read())
    print(result)

{'encoding': 'UTF-8-SIG', 'confidence': 1.0, 'language': ''}

This was done since a few models were tried and their encoding was not UTF-8 and needed to be specified.

In [4]:
# Load the spaCy model for selected language
nlp = spacy.load(config['spacy_model'])
df = pd.read_csv("bg_final.csv", nrows=10)

In [5]:
df.head()

,dialogue_id,utterance_id,sentence_id,topic,dialog_act,emotion,sentence_text,sentence_text_bg
0,0,0,0,Ordinary Life,directive,disgust,The kitchen stinks .,Кухнята мирише.
1,0,1,0,Ordinary Life,commissive,no emotion,I'll throw out the garbage .,Ще изхвърля боклука.
2,1,0,0,Ordinary Life,directive,happiness,"So Dick , how about getting some coffee for to...","Така че Dick , какво ще кажете за получаване н..."
3,1,1,0,Ordinary Life,commissive,disgust,Coffee ?,Кафе ?
4,1,1,1,Ordinary Life,commissive,disgust,I don ’ t honestly like that kind of stuff .,"Честно казано, не харесвам такива неща."

In [6]:
# Process each sentence and store POS tags in a new column
df['POS_Tags'] = df['sentence_text_bg'].apply(lambda text: [token.pos_ for token in nlp(text)])

# Display the updated DataFrame
df.head(10)

,dialogue_id,utterance_id,sentence_id,topic,dialog_act,emotion,sentence_text,sentence_text_bg,POS_Tags
0,0,0,0,Ordinary Life,directive,disgust,The kitchen stinks .,Кухнята мирише.,"[NOUN, VERB, PUNCT]"
1,0,1,0,Ordinary Life,commissive,no emotion,I'll throw out the garbage .,Ще изхвърля боклука.,"[AUX, VERB, NOUN, PUNCT]"
2,1,0,0,Ordinary Life,directive,happiness,"So Dick , how about getting some coffee for to...","Така че Dick , какво ще кажете за получаване н...","[ADV, SCONJ, PROPN, PUNCT, DET, AUX, VERB, ADP..."
3,1,1,0,Ordinary Life,commissive,disgust,Coffee ?,Кафе ?,"[NOUN, PUNCT]"
4,1,1,1,Ordinary Life,commissive,disgust,I don ’ t honestly like that kind of stuff .,"Честно казано, не харесвам такива неща.","[ADV, ADJ, PUNCT, PART, VERB, DET, DET, PUNCT]"
5,1,2,0,Ordinary Life,directive,no emotion,"Come on , you can at least try a little , besi...","Хайде , можеш поне да опиташ малко , освен циг...","[PART, PUNCT, VERB, ADV, AUX, VERB, ADV, PUNCT..."
6,1,3,0,Ordinary Life,inform,anger,What ’ s wrong with that ?,Какво не е наред с това?,"[DET, PART, AUX, ADV, ADP, PRON, PUNCT]"
7,1,3,1,Ordinary Life,inform,anger,Cigarette is the thing I go crazy for .,"Цигарата е нещото, по което полудявам.","[NOUN, AUX, NOUN, PUNCT, ADP, PRON, VERB, PUNCT]"
8,1,4,0,Ordinary Life,inform,no emotion,"Not for me , Dick .","Не и за мен, Дик.","[PART, CCONJ, ADP, PRON, PUNCT, PROPN, PUNCT]"
9,2,0,0,Ordinary Life,question,no emotion,Are things still going badly with your housegu...,Все още ли нещата с вашия съквартирант вървят ...,"[ADV, ADV, PART, PRON, ADP, DET, NOUN, VERB, A..."

The bg_news_lg model is one of a small number of high-quality Bulgarian pipelines available for spaCy. It is a large model (version 3.5.4) trained on the Bulgarian Treebank (UD_Bulgarian-BTB) and includes a POS tagger component. The “large” size with ~200,000 Floret word vectors of dimension 300 improves its ability to cover diverse word forms, reducing the number of out-of-vocabulary tokens. Although it was trained on news domain text , which is more formal and grammatical , the model is is among the few that integrate directly into the spaCy pipeline, with large pretrained vectors, and is very easy to use for feature extraction.

## Subtask 2: Term Frequency-Inverse Document Frequency (TF-IDF)

In [7]:
# Import necessary libraries
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize the TF-IDF Vectorizer
vectorizer = TfidfVectorizer()

# Fit and transform the text data to get the TF-IDF matrix
tfidf_matrix = vectorizer.fit_transform(df['sentence_text_bg'])

def get_nonzero_with_features(row):
    dense_row = row.toarray().flatten()
    nonzero_indices = dense_row.nonzero()[0]
    nonzero_values = dense_row[nonzero_indices]
    feature_names = vectorizer.get_feature_names_out()
    return [(feature_names[idx], float(val)) for idx, val in zip(nonzero_indices, nonzero_values)]

# Create a column "TF-IDF" in the DataFrame to store the TF-IDF vectors
df["TF-IDF"] = [get_nonzero_with_features(row) for row in tfidf_matrix]

df.head(10)

,dialogue_id,utterance_id,sentence_id,topic,dialog_act,emotion,sentence_text,sentence_text_bg,POS_Tags,TF-IDF
0,0,0,0,Ordinary Life,directive,disgust,The kitchen stinks .,Кухнята мирише.,"[NOUN, VERB, PUNCT]","[(кухнята, 0.7071067811865475), (мирише, 0.707..."
1,0,1,0,Ordinary Life,commissive,no emotion,I'll throw out the garbage .,Ще изхвърля боклука.,"[AUX, VERB, NOUN, PUNCT]","[(боклука, 0.6060433187339399), (изхвърля, 0.6..."
2,1,0,0,Ordinary Life,directive,happiness,"So Dick , how about getting some coffee for to...","Така че Dick , какво ще кажете за получаване н...","[ADV, SCONJ, PROPN, PUNCT, DET, AUX, VERB, ADP...","[(dick, 0.2693740845690302), (вечер, 0.2693740..."
3,1,1,0,Ordinary Life,commissive,disgust,Coffee ?,Кафе ?,"[NOUN, PUNCT]","[(кафе, 1.0)]"
4,1,1,1,Ordinary Life,commissive,disgust,I don ’ t honestly like that kind of stuff .,"Честно казано, не харесвам такива неща.","[ADV, ADJ, PUNCT, PART, VERB, DET, DET, PUNCT]","[(казано, 0.42435658024974), (не, 0.3156065018..."
5,1,2,0,Ordinary Life,directive,no emotion,"Come on , you can at least try a little , besi...","Хайде , можеш поне да опиташ малко , освен циг...","[PART, PUNCT, VERB, ADV, AUX, VERB, ADV, PUNCT...","[(да, 0.34410595277587486), (малко, 0.29252149..."
6,1,3,0,Ordinary Life,inform,anger,What ’ s wrong with that ?,Какво не е наред с това?,"[DET, PART, AUX, ADV, ADP, PRON, PUNCT]","[(какво, 0.46968603824569793), (наред, 0.55251..."
7,1,3,1,Ordinary Life,inform,anger,Cigarette is the thing I go crazy for .,"Цигарата е нещото, по което полудявам.","[NOUN, AUX, NOUN, PUNCT, ADP, PRON, VERB, PUNCT]","[(което, 0.4601578921271882), (нещото, 0.46015..."
8,1,4,0,Ordinary Life,inform,no emotion,"Not for me , Dick .","Не и за мен, Дик.","[PART, CCONJ, ADP, PRON, PUNCT, PROPN, PUNCT]","[(дик, 0.5525124243793842), (за, 0.46968603824..."
9,2,0,0,Ordinary Life,question,no emotion,Are things still going badly with your housegu...,Все още ли нещата с вашия съквартирант вървят ...,"[ADV, ADV, PART, PRON, ADP, DET, NOUN, VERB, A...","[(вашия, 0.35355339059327373), (все, 0.3535533..."

# Subtask 3: Sentiment Analysis

In [8]:
pip install torch torchvision torchaudio --index-url

Note: you may need to restart the kernel to use updated packages.

In [9]:
# Check PyTorch version
import torch
print(torch.__version__)

2.8.0+cpu

In [10]:
from transformers import pipeline

# Load a multilingual sentiment analysis model
sentiment_classifier = pipeline(
    model="lxyuan/distilbert-base-multilingual-cased-sentiments-student",
    top_k=None
)

# Extract sentiment scores (positive - negative) for consistency with "Sentiment_Score"
def get_sentiment_score(text):
    result = sentiment_classifier(text)[0]  # list of dicts
    scores = {r['label']: r['score'] for r in result}
    return scores.get('positive', 0) - scores.get('negative', 0)

df['Sentiment_Score'] = df['sentence_text_bg'].apply(get_sentiment_score)
df.head(10)

,dialogue_id,utterance_id,sentence_id,topic,dialog_act,emotion,sentence_text,sentence_text_bg,POS_Tags,TF-IDF,Sentiment_Score
0,0,0,0,Ordinary Life,directive,disgust,The kitchen stinks .,Кухнята мирише.,"[NOUN, VERB, PUNCT]","[(кухнята, 0.7071067811865475), (мирише, 0.707...",0.385488
1,0,1,0,Ordinary Life,commissive,no emotion,I'll throw out the garbage .,Ще изхвърля боклука.,"[AUX, VERB, NOUN, PUNCT]","[(боклука, 0.6060433187339399), (изхвърля, 0.6...",-0.184246
2,1,0,0,Ordinary Life,directive,happiness,"So Dick , how about getting some coffee for to...","Така че Dick , какво ще кажете за получаване н...","[ADV, SCONJ, PROPN, PUNCT, DET, AUX, VERB, ADP...","[(dick, 0.2693740845690302), (вечер, 0.2693740...",-0.122162
3,1,1,0,Ordinary Life,commissive,disgust,Coffee ?,Кафе ?,"[NOUN, PUNCT]","[(кафе, 1.0)]",-0.163817
4,1,1,1,Ordinary Life,commissive,disgust,I don ’ t honestly like that kind of stuff .,"Честно казано, не харесвам такива неща.","[ADV, ADJ, PUNCT, PART, VERB, DET, DET, PUNCT]","[(казано, 0.42435658024974), (не, 0.3156065018...",-0.176561
5,1,2,0,Ordinary Life,directive,no emotion,"Come on , you can at least try a little , besi...","Хайде , можеш поне да опиташ малко , освен циг...","[PART, PUNCT, VERB, ADV, AUX, VERB, ADV, PUNCT...","[(да, 0.34410595277587486), (малко, 0.29252149...",0.024798
6,1,3,0,Ordinary Life,inform,anger,What ’ s wrong with that ?,Какво не е наред с това?,"[DET, PART, AUX, ADV, ADP, PRON, PUNCT]","[(какво, 0.46968603824569793), (наред, 0.55251...",-0.198530
7,1,3,1,Ordinary Life,inform,anger,Cigarette is the thing I go crazy for .,"Цигарата е нещото, по което полудявам.","[NOUN, AUX, NOUN, PUNCT, ADP, PRON, VERB, PUNCT]","[(което, 0.4601578921271882), (нещото, 0.46015...",-0.239203
8,1,4,0,Ordinary Life,inform,no emotion,"Not for me , Dick .","Не и за мен, Дик.","[PART, CCONJ, ADP, PRON, PUNCT, PROPN, PUNCT]","[(дик, 0.5525124243793842), (за, 0.46968603824...",-0.075781
9,2,0,0,Ordinary Life,question,no emotion,Are things still going badly with your housegu...,Все още ли нещата с вашия съквартирант вървят ...,"[ADV, ADV, PART, PRON, ADP, DET, NOUN, VERB, A...","[(вашия, 0.35355339059327373), (все, 0.3535533...",-0.287767

The “lxyuan/distilbert-base-multilingual-cased-sentiments-student” model was selected because it is a distilled multilingual model that supports Bulgarian among other languages. Given that TextBlob and VADER do not reliably cover Bulgarian sentiment, this model offers a more suitable alternative. It balances efficiency (being a student-distilled model) with multilingual capability, making it a practical choice for extracting sentiment scores for Bulgarian transcripts.

## Subtask 4: Pretrained Word Embeddings

In [11]:
import pandas as pd
import numpy as np
from gensim.models.fasttext import load_facebook_model
import re

### Pretrained Word Embeddings with fastText

In [13]:
# Load the pretrained FastText model
ft_model = load_facebook_model('cc.bg.300.bin')
print("Model loaded successfully.")

text_column = 'sentence_text_bg'


def sentence_to_vector(sentence, model):
    word_vectors_model = model.wv
    words = re.findall(r'\b\w+\b', str(sentence).lower())

    word_vectors = []
    for word in words:
        if word in word_vectors_model:
            word_vectors.append(word_vectors_model[word])

    if not word_vectors:
        # If no word matches, return a zero vector (same size as model’s vectors)
        return np.zeros(word_vectors_model.vector_size, dtype=np.float32)
    # Average the word vectors to get the sentence vector
    return np.mean(word_vectors, axis=0)


df['Pretrained_Embeddings'] = df[text_column].apply(lambda s: sentence_to_vector(s, ft_model))

print("\n--- Results ---")
print(df[['sentence_text_bg', 'Pretrained_Embeddings']].head())

Model loaded successfully.

--- Results ---
                                    sentence_text_bg  \
0                                    Кухнята мирише.
1                               Ще изхвърля боклука.
2  Така че Dick , какво ще кажете за получаване н...
3                                             Кафе ?
4            Честно казано, не харесвам такива неща.

                               Pretrained_Embeddings
0  [-0.05895353, 0.02678768, 0.011074896, 0.03241...
1  [-0.05321903, 0.008844021, 0.07036609, 0.04865...
2  [-0.0032325375, -0.014675511, 0.024256792, 0.0...
3  [0.0019401921, 0.03712749, 0.025385574, 0.0153...
4  [0.00017724124, -0.039979186, 0.014543567, 0.0...

The Facebook fastText Filipino model “cc.bg.300.bin” was used because it provides pretrained word vectors for Bulgarian, trained on Common Crawl + Wikipedia data.
The vectors are 300-dimensional, and the model uses character n-grams (subword information) so that even rare or previously unseen word forms can be represented via their subword parts.
Because our transcripts are in Bulgarian, this model is well-matched in language, giving broad vocabulary coverage and allowing us to build sentence vectors by averaging. This method yields fixed-size embeddings for each sentence that can serve as input features.

More advanced models, such as FastText, address the OOV problem by generating word vectors from character n-grams (subwords).  For instance, the word apple can be broken down into subwords like <ap, app, ppl, ple>, and <apple>. If the word apples is not in the vocabulary, the model can still construct a vector for it by averaging the vectors of its known subwords. This is particularly effective for morphologically rich languages and for handling misspellings or rare words.

In [14]:
df.head(10)

,dialogue_id,utterance_id,sentence_id,topic,dialog_act,emotion,sentence_text,sentence_text_bg,POS_Tags,TF-IDF,Sentiment_Score,Pretrained_Embeddings
0,0,0,0,Ordinary Life,directive,disgust,The kitchen stinks .,Кухнята мирише.,"[NOUN, VERB, PUNCT]","[(кухнята, 0.7071067811865475), (мирише, 0.707...",0.385488,"[-0.05895353, 0.02678768, 0.011074896, 0.03241..."
1,0,1,0,Ordinary Life,commissive,no emotion,I'll throw out the garbage .,Ще изхвърля боклука.,"[AUX, VERB, NOUN, PUNCT]","[(боклука, 0.6060433187339399), (изхвърля, 0.6...",-0.184246,"[-0.05321903, 0.008844021, 0.07036609, 0.04865..."
2,1,0,0,Ordinary Life,directive,happiness,"So Dick , how about getting some coffee for to...","Така че Dick , какво ще кажете за получаване н...","[ADV, SCONJ, PROPN, PUNCT, DET, AUX, VERB, ADP...","[(dick, 0.2693740845690302), (вечер, 0.2693740...",-0.122162,"[-0.0032325375, -0.014675511, 0.024256792, 0.0..."
3,1,1,0,Ordinary Life,commissive,disgust,Coffee ?,Кафе ?,"[NOUN, PUNCT]","[(кафе, 1.0)]",-0.163817,"[0.0019401921, 0.03712749, 0.025385574, 0.0153..."
4,1,1,1,Ordinary Life,commissive,disgust,I don ’ t honestly like that kind of stuff .,"Честно казано, не харесвам такива неща.","[ADV, ADJ, PUNCT, PART, VERB, DET, DET, PUNCT]","[(казано, 0.42435658024974), (не, 0.3156065018...",-0.176561,"[0.00017724124, -0.039979186, 0.014543567, 0.0..."
5,1,2,0,Ordinary Life,directive,no emotion,"Come on , you can at least try a little , besi...","Хайде , можеш поне да опиташ малко , освен циг...","[PART, PUNCT, VERB, ADV, AUX, VERB, ADV, PUNCT...","[(да, 0.34410595277587486), (малко, 0.29252149...",0.024798,"[0.021950508, -0.041999117, 0.0140455365, 0.01..."
6,1,3,0,Ordinary Life,inform,anger,What ’ s wrong with that ?,Какво не е наред с това?,"[DET, PART, AUX, ADV, ADP, PRON, PUNCT]","[(какво, 0.46968603824569793), (наред, 0.55251...",-0.198530,"[-0.00087265484, -0.02994658, 0.005080737, 0.0..."
7,1,3,1,Ordinary Life,inform,anger,Cigarette is the thing I go crazy for .,"Цигарата е нещото, по което полудявам.","[NOUN, AUX, NOUN, PUNCT, ADP, PRON, VERB, PUNCT]","[(което, 0.4601578921271882), (нещото, 0.46015...",-0.239203,"[0.022024015, -0.015521896, -0.003359329, 0.00..."
8,1,4,0,Ordinary Life,inform,no emotion,"Not for me , Dick .","Не и за мен, Дик.","[PART, CCONJ, ADP, PRON, PUNCT, PROPN, PUNCT]","[(дик, 0.5525124243793842), (за, 0.46968603824...",-0.075781,"[-0.018605703, -0.014853599, -0.021822492, 0.0..."
9,2,0,0,Ordinary Life,question,no emotion,Are things still going badly with your housegu...,Все още ли нещата с вашия съквартирант вървят ...,"[ADV, ADV, PART, PRON, ADP, DET, NOUN, VERB, A...","[(вашия, 0.35355339059327373), (все, 0.3535533...",-0.287767,"[-0.018371671, -0.009949706, -0.030019002, 0.0..."

## Subtask 5: Custom Word Embedding Model

In [15]:
import logging
from gensim.models import Word2Vec
from gensim.models.word2vec import LineSentence

# Configure logging to monitor training progress
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

# Path to the text corpus file
corpus_file = 'bulgarian_corpus.txt'
print(f"Loading sentences from {corpus_file}...")

# LineSentence streams the corpus sentence by sentence to save memory
sentences = LineSentence(corpus_file)

# Train a Word2Vec model on the corpus
custom_model = Word2Vec(
    sentences=sentences,
    vector_size=150,
    window=5,
    min_count=5,
    sg=1,
    workers=4
)

# Save the trained model to disk
model_save_path = "bulgarian_wiki_word2vec.model"
custom_model.save(model_save_path)

# Column to store custom embeddings
df['Custom_Embeddings'] = df[text_column].apply(lambda s: sentence_to_vector(s, custom_model))

df.head(10)

2025-09-18 15:20:22,913 : INFO : collecting all words and their counts
2025-09-18 15:20:22,917 : INFO : PROGRESS: at sentence #0, processed 0 words, keeping 0 word types

Loading sentences from bulgarian_corpus.txt...

2025-09-18 15:20:24,444 : INFO : PROGRESS: at sentence #10000, processed 6963634 words, keeping 309368 word types
2025-09-18 15:20:25,900 : INFO : PROGRESS: at sentence #20000, processed 13561591 words, keeping 483464 word types
2025-09-18 15:20:27,017 : INFO : PROGRESS: at sentence #30000, processed 18618160 words, keeping 595302 word types
2025-09-18 15:20:27,990 : INFO : PROGRESS: at sentence #40000, processed 23001334 words, keeping 678393 word types
2025-09-18 15:20:28,899 : INFO : PROGRESS: at sentence #50000, processed 26985870 words, keeping 760506 word types
2025-09-18 15:20:29,687 : INFO : PROGRESS: at sentence #60000, processed 30503578 words, keeping 830242 word types
2025-09-18 15:20:30,412 : INFO : PROGRESS: at sentence #70000, processed 33744747 words, keeping 886142 word types
2025-09-18 15:20:31,077 : INFO : PROGRESS: at sentence #80000, processed 36701749 words, keeping 932878 word types
2025-09-18 15:20:31,723 : INFO : PROGRESS: at sentence #90000, processed 39558483 words, keeping 980169 word types
2025-09-18 15:20:32,441 : INFO : PROGRESS: at sentence #100000, processed 42748103 words, keeping 1038979 word types
2025-09-18 15:20:33,225 : INFO : PROGRESS: at sentence #110000, processed 46061279 words, keeping 1095680 word types
2025-09-18 15:20:33,898 : INFO : PROGRESS: at sentence #120000, processed 48999354 words, keeping 1144257 word types
2025-09-18 15:20:34,633 : INFO : PROGRESS: at sentence #130000, processed 52269984 words, keeping 1189837 word types
2025-09-18 15:20:35,304 : INFO : PROGRESS: at sentence #140000, processed 55189878 words, keeping 1231398 word types
2025-09-18 15:20:35,850 : INFO : PROGRESS: at sentence #150000, processed 57591130 words, keeping 1263373 word types
2025-09-18 15:20:36,596 : INFO : PROGRESS: at sentence #160000, processed 60856157 words, keeping 1306266 word types
2025-09-18 15:20:37,405 : INFO : PROGRESS: at sentence #170000, processed 64345697 words, keeping 1354309 word types
2025-09-18 15:20:38,164 : INFO : PROGRESS: at sentence #180000, processed 67435185 words, keeping 1399393 word types
2025-09-18 15:20:38,903 : INFO : PROGRESS: at sentence #190000, processed 70708643 words, keeping 1439337 word types
2025-09-18 15:20:39,633 : INFO : PROGRESS: at sentence #200000, processed 73976013 words, keeping 1481112 word types
2025-09-18 15:20:40,403 : INFO : PROGRESS: at sentence #210000, processed 77396548 words, keeping 1528917 word types
2025-09-18 15:20:41,202 : INFO : PROGRESS: at sentence #220000, processed 80732975 words, keeping 1571718 word types
2025-09-18 15:20:42,041 : INFO : PROGRESS: at sentence #230000, processed 84068825 words, keeping 1616281 word types
2025-09-18 15:20:42,896 : INFO : PROGRESS: at sentence #240000, processed 87365474 words, keeping 1658181 word types
2025-09-18 15:20:42,986 : INFO : collected 1661477 word types from a corpus of 87699304 raw words and 241208 sentences
2025-09-18 15:20:42,987 : INFO : Creating a fresh vocabulary
2025-09-18 15:20:43,921 : INFO : Word2Vec lifecycle event {'msg': 'effective_min_count=5 retains 416079 unique words (25.04% of original 1661477, drops 1245398)', 'datetime': '2025-09-18T15:20:43.921122', 'gensim': '4.3.3', 'python': '3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]', 'platform': 'Windows-10-10.0.26100-SP0', 'event': 'prepare_vocab'}
2025-09-18 15:20:43,921 : INFO : Word2Vec lifecycle event {'msg': 'effective_min_count=5 leaves 85804516 word corpus (97.84% of original 87699304, drops 1894788)', 'datetime': '2025-09-18T15:20:43.921122', 'gensim': '4.3.3', 'python': '3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]', 'platform': 'Windows-10-10.0.26100-SP0', 'event': 'prepare_vocab'}
2025-09-18 15:20:44,928 : INFO : deleting the raw counts dictionary of 1661477 items
2025-09-18 15:20:44,971 : INFO : sample=0.001 downsamples 19 most-common words
2025-09-18 15:20:44,972 : INFO : Word2Vec lifecycle event {'msg': 'downsampling leaves estimated 74957187.68195322 word corpus (87.4%% of prior 85804516)', 'datetime': '2025-09-18T15:20:44.972691', 'gensim': '4.3.3', 'python': '3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]', 'platform': 'Windows-10-10.0.26100-SP0', 'event': 'prepare_vocab'}
2025-09-18 15:20:46,616 : INFO : estimated required memory for 416079 words and 150 dimensions: 707334300 bytes
2025-09-18 15:20:46,616 : INFO : resetting layer weights
2025-09-18 15:20:46,771 : INFO : Word2Vec lifecycle event {'update': False, 'trim_rule': 'None', 'datetime': '2025-09-18T15:20:46.771956', 'gensim': '4.3.3', 'python': '3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]', 'platform': 'Windows-10-10.0.26100-SP0', 'event': 'build_vocab'}
2025-09-18 15:20:46,771 : INFO : Word2Vec lifecycle event {'msg': 'training model with 4 workers on 416079 vocabulary and 150 features, using sg=1 hs=0 sample=0.001 negative=5 window=5 shrink_windows=True', 'datetime': '2025-09-18T15:20:46.771956', 'gensim': '4.3.3', 'python': '3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]', 'platform': 'Windows-10-10.0.26100-SP0', 'event': 'train'}
2025-09-18 15:20:47,811 : INFO : EPOCH 0 - PROGRESS: at 0.23% examples, 385467 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:20:48,817 : INFO : EPOCH 0 - PROGRESS: at 0.37% examples, 383127 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:20:49,820 : INFO : EPOCH 0 - PROGRESS: at 0.47% examples, 388035 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:20:50,840 : INFO : EPOCH 0 - PROGRESS: at 0.63% examples, 388535 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:20:51,863 : INFO : EPOCH 0 - PROGRESS: at 0.99% examples, 391518 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:20:52,872 : INFO : EPOCH 0 - PROGRESS: at 1.58% examples, 392865 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:20:53,879 : INFO : EPOCH 0 - PROGRESS: at 1.98% examples, 394848 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:20:54,885 : INFO : EPOCH 0 - PROGRESS: at 2.25% examples, 392459 words/s, in_qsize 8, out_qsize 0
2025-09-18 15:20:55,891 : INFO : EPOCH 0 - PROGRESS: at 2.51% examples, 390058 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:20:56,911 : INFO : EPOCH 0 - PROGRESS: at 2.79% examples, 390125 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:20:57,918 : INFO : EPOCH 0 - PROGRESS: at 3.07% examples, 390369 words/s, in_qsize 8, out_qsize 0
2025-09-18 15:20:58,919 : INFO : EPOCH 0 - PROGRESS: at 3.42% examples, 391626 words/s, in_qsize 8, out_qsize 0
2025-09-18 15:20:59,932 : INFO : EPOCH 0 - PROGRESS: at 3.62% examples, 389282 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:00,944 : INFO : EPOCH 0 - PROGRESS: at 3.80% examples, 387945 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:01,946 : INFO : EPOCH 0 - PROGRESS: at 4.08% examples, 387201 words/s, in_qsize 8, out_qsize 0
2025-09-18 15:21:02,979 : INFO : EPOCH 0 - PROGRESS: at 4.31% examples, 385387 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:03,985 : INFO : EPOCH 0 - PROGRESS: at 4.54% examples, 384330 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:04,997 : INFO : EPOCH 0 - PROGRESS: at 4.77% examples, 383341 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:06,014 : INFO : EPOCH 0 - PROGRESS: at 5.04% examples, 383398 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:07,040 : INFO : EPOCH 0 - PROGRESS: at 5.26% examples, 382793 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:08,070 : INFO : EPOCH 0 - PROGRESS: at 5.48% examples, 379174 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:09,075 : INFO : EPOCH 0 - PROGRESS: at 5.77% examples, 378625 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:10,081 : INFO : EPOCH 0 - PROGRESS: at 6.04% examples, 378343 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:11,088 : INFO : EPOCH 0 - PROGRESS: at 6.35% examples, 378749 words/s, in_qsize 8, out_qsize 0
2025-09-18 15:21:12,114 : INFO : EPOCH 0 - PROGRESS: at 6.66% examples, 378565 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:13,152 : INFO : EPOCH 0 - PROGRESS: at 6.92% examples, 376282 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:14,189 : INFO : EPOCH 0 - PROGRESS: at 7.17% examples, 373511 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:15,191 : INFO : EPOCH 0 - PROGRESS: at 7.41% examples, 372477 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:16,203 : INFO : EPOCH 0 - PROGRESS: at 7.70% examples, 371322 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:17,222 : INFO : EPOCH 0 - PROGRESS: at 8.00% examples, 370271 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:18,230 : INFO : EPOCH 0 - PROGRESS: at 8.29% examples, 369044 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:19,309 : INFO : EPOCH 0 - PROGRESS: at 8.54% examples, 365059 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:20,354 : INFO : EPOCH 0 - PROGRESS: at 8.76% examples, 362065 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:21,354 : INFO : EPOCH 0 - PROGRESS: at 8.98% examples, 359178 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:22,360 : INFO : EPOCH 0 - PROGRESS: at 9.21% examples, 356539 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:23,370 : INFO : EPOCH 0 - PROGRESS: at 9.45% examples, 353939 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:24,427 : INFO : EPOCH 0 - PROGRESS: at 9.69% examples, 350816 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:25,446 : INFO : EPOCH 0 - PROGRESS: at 9.95% examples, 348297 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:26,455 : INFO : EPOCH 0 - PROGRESS: at 10.23% examples, 346465 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:27,458 : INFO : EPOCH 0 - PROGRESS: at 10.50% examples, 345171 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:28,471 : INFO : EPOCH 0 - PROGRESS: at 10.86% examples, 344922 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:29,526 : INFO : EPOCH 0 - PROGRESS: at 11.24% examples, 345136 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:30,527 : INFO : EPOCH 0 - PROGRESS: at 11.60% examples, 345355 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:31,530 : INFO : EPOCH 0 - PROGRESS: at 11.96% examples, 345817 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:32,538 : INFO : EPOCH 0 - PROGRESS: at 12.31% examples, 345685 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:33,583 : INFO : EPOCH 0 - PROGRESS: at 12.72% examples, 345808 words/s, in_qsize 8, out_qsize 0
2025-09-18 15:21:34,608 : INFO : EPOCH 0 - PROGRESS: at 13.12% examples, 346214 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:35,634 : INFO : EPOCH 0 - PROGRESS: at 13.51% examples, 346467 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:36,649 : INFO : EPOCH 0 - PROGRESS: at 13.88% examples, 346503 words/s, in_qsize 6, out_qsize 1
2025-09-18 15:21:37,675 : INFO : EPOCH 0 - PROGRESS: at 14.26% examples, 346927 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:38,678 : INFO : EPOCH 0 - PROGRESS: at 14.67% examples, 347340 words/s, in_qsize 8, out_qsize 0
2025-09-18 15:21:39,702 : INFO : EPOCH 0 - PROGRESS: at 15.08% examples, 347642 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:40,706 : INFO : EPOCH 0 - PROGRESS: at 15.43% examples, 347995 words/s, in_qsize 6, out_qsize 0
2025-09-18 15:21:41,708 : INFO : EPOCH 0 - PROGRESS: at 15.90% examples, 348124 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:42,715 : INFO : EPOCH 0 - PROGRESS: at 16.35% examples, 348379 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:43,719 : INFO : EPOCH 0 - PROGRESS: at 16.82% examples, 348785 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:44,748 : INFO : EPOCH 0 - PROGRESS: at 17.27% examples, 348920 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:45,750 : INFO : EPOCH 0 - PROGRESS: at 17.69% examples, 349234 words/s, in_qsize 8, out_qsize 0
2025-09-18 15:21:46,770 : INFO : EPOCH 0 - PROGRESS: at 18.15% examples, 349403 words/s, in_qsize 8, out_qsize 0
2025-09-18 15:21:47,797 : INFO : EPOCH 0 - PROGRESS: at 18.60% examples, 349594 words/s, in_qsize 8, out_qsize 0
2025-09-18 15:21:48,839 : INFO : EPOCH 0 - PROGRESS: at 19.04% examples, 349788 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:49,846 : INFO : EPOCH 0 - PROGRESS: at 19.48% examples, 349975 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:50,869 : INFO : EPOCH 0 - PROGRESS: at 19.90% examples, 350267 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:51,872 : INFO : EPOCH 0 - PROGRESS: at 20.36% examples, 350493 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:52,916 : INFO : EPOCH 0 - PROGRESS: at 20.85% examples, 350617 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:53,953 : INFO : EPOCH 0 - PROGRESS: at 21.38% examples, 350909 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:54,981 : INFO : EPOCH 0 - PROGRESS: at 21.90% examples, 351153 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:56,025 : INFO : EPOCH 0 - PROGRESS: at 22.44% examples, 350995 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:57,026 : INFO : EPOCH 0 - PROGRESS: at 22.98% examples, 351344 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:58,047 : INFO : EPOCH 0 - PROGRESS: at 23.50% examples, 351363 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:21:59,057 : INFO : EPOCH 0 - PROGRESS: at 23.94% examples, 351362 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:00,063 : INFO : EPOCH 0 - PROGRESS: at 24.42% examples, 351429 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:01,070 : INFO : EPOCH 0 - PROGRESS: at 24.92% examples, 351496 words/s, in_qsize 6, out_qsize 1
2025-09-18 15:22:02,088 : INFO : EPOCH 0 - PROGRESS: at 25.42% examples, 351593 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:03,098 : INFO : EPOCH 0 - PROGRESS: at 25.91% examples, 351805 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:04,107 : INFO : EPOCH 0 - PROGRESS: at 26.45% examples, 351849 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:05,140 : INFO : EPOCH 0 - PROGRESS: at 27.07% examples, 351931 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:06,142 : INFO : EPOCH 0 - PROGRESS: at 27.63% examples, 352067 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:07,151 : INFO : EPOCH 0 - PROGRESS: at 28.18% examples, 352090 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:08,164 : INFO : EPOCH 0 - PROGRESS: at 28.74% examples, 352217 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:09,186 : INFO : EPOCH 0 - PROGRESS: at 29.27% examples, 352107 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:10,197 : INFO : EPOCH 0 - PROGRESS: at 29.84% examples, 352252 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:11,198 : INFO : EPOCH 0 - PROGRESS: at 30.35% examples, 352228 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:12,211 : INFO : EPOCH 0 - PROGRESS: at 30.95% examples, 352173 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:13,213 : INFO : EPOCH 0 - PROGRESS: at 31.40% examples, 351758 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:14,220 : INFO : EPOCH 0 - PROGRESS: at 31.94% examples, 351252 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:15,235 : INFO : EPOCH 0 - PROGRESS: at 32.60% examples, 351301 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:16,257 : INFO : EPOCH 0 - PROGRESS: at 33.19% examples, 350998 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:17,273 : INFO : EPOCH 0 - PROGRESS: at 33.89% examples, 350928 words/s, in_qsize 8, out_qsize 0
2025-09-18 15:22:18,310 : INFO : EPOCH 0 - PROGRESS: at 34.50% examples, 350941 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:19,325 : INFO : EPOCH 0 - PROGRESS: at 35.15% examples, 351127 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:20,328 : INFO : EPOCH 0 - PROGRESS: at 35.75% examples, 351323 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:21,366 : INFO : EPOCH 0 - PROGRESS: at 36.35% examples, 351375 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:22,369 : INFO : EPOCH 0 - PROGRESS: at 36.93% examples, 351347 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:23,378 : INFO : EPOCH 0 - PROGRESS: at 37.42% examples, 351044 words/s, in_qsize 8, out_qsize 0
2025-09-18 15:22:24,381 : INFO : EPOCH 0 - PROGRESS: at 37.90% examples, 350697 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:25,402 : INFO : EPOCH 0 - PROGRESS: at 38.42% examples, 350236 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:26,420 : INFO : EPOCH 0 - PROGRESS: at 38.95% examples, 349986 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:27,469 : INFO : EPOCH 0 - PROGRESS: at 39.53% examples, 349793 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:28,491 : INFO : EPOCH 0 - PROGRESS: at 40.10% examples, 350084 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:29,500 : INFO : EPOCH 0 - PROGRESS: at 40.61% examples, 349899 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:30,502 : INFO : EPOCH 0 - PROGRESS: at 41.10% examples, 350027 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:31,504 : INFO : EPOCH 0 - PROGRESS: at 41.68% examples, 350163 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:32,514 : INFO : EPOCH 0 - PROGRESS: at 42.23% examples, 350271 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:33,527 : INFO : EPOCH 0 - PROGRESS: at 42.75% examples, 350424 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:34,544 : INFO : EPOCH 0 - PROGRESS: at 43.30% examples, 350666 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:35,573 : INFO : EPOCH 0 - PROGRESS: at 43.81% examples, 350725 words/s, in_qsize 8, out_qsize 0
2025-09-18 15:22:36,586 : INFO : EPOCH 0 - PROGRESS: at 44.35% examples, 350920 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:37,594 : INFO : EPOCH 0 - PROGRESS: at 44.86% examples, 351004 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:38,615 : INFO : EPOCH 0 - PROGRESS: at 45.41% examples, 351128 words/s, in_qsize 8, out_qsize 0
2025-09-18 15:22:39,673 : INFO : EPOCH 0 - PROGRESS: at 46.07% examples, 351110 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:40,676 : INFO : EPOCH 0 - PROGRESS: at 46.66% examples, 351295 words/s, in_qsize 8, out_qsize 0
2025-09-18 15:22:41,697 : INFO : EPOCH 0 - PROGRESS: at 47.29% examples, 351402 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:42,702 : INFO : EPOCH 0 - PROGRESS: at 47.95% examples, 351559 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:43,702 : INFO : EPOCH 0 - PROGRESS: at 48.54% examples, 351754 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:44,706 : INFO : EPOCH 0 - PROGRESS: at 49.16% examples, 351923 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:45,717 : INFO : EPOCH 0 - PROGRESS: at 49.72% examples, 351983 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:46,745 : INFO : EPOCH 0 - PROGRESS: at 50.32% examples, 352142 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:47,767 : INFO : EPOCH 0 - PROGRESS: at 50.85% examples, 352205 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:48,781 : INFO : EPOCH 0 - PROGRESS: at 51.40% examples, 352242 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:49,793 : INFO : EPOCH 0 - PROGRESS: at 51.93% examples, 352156 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:50,814 : INFO : EPOCH 0 - PROGRESS: at 52.48% examples, 352154 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:51,859 : INFO : EPOCH 0 - PROGRESS: at 52.94% examples, 352173 words/s, in_qsize 8, out_qsize 0
2025-09-18 15:22:52,895 : INFO : EPOCH 0 - PROGRESS: at 53.48% examples, 352176 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:53,901 : INFO : EPOCH 0 - PROGRESS: at 54.07% examples, 352312 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:54,914 : INFO : EPOCH 0 - PROGRESS: at 54.67% examples, 352381 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:55,934 : INFO : EPOCH 0 - PROGRESS: at 55.38% examples, 352450 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:56,954 : INFO : EPOCH 0 - PROGRESS: at 55.85% examples, 352432 words/s, in_qsize 8, out_qsize 0
2025-09-18 15:22:57,981 : INFO : EPOCH 0 - PROGRESS: at 56.48% examples, 352448 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:22:58,996 : INFO : EPOCH 0 - PROGRESS: at 57.03% examples, 352464 words/s, in_qsize 7, out_qsize 0
2025-09-18 15:23:00,034 : INFO : EPOCH 0 - PROGRESS: at 57.61% examples, 352472 words/s, in_qsize 7, out_qsize 0

,dialogue_id,utterance_id,sentence_id,topic,dialog_act,emotion,sentence_text,sentence_text_bg,POS_Tags,TF-IDF,Sentiment_Score,Pretrained_Embeddings,Custom_Embeddings
0,0,0,0,Ordinary Life,directive,disgust,The kitchen stinks .,Кухнята мирише.,"[NOUN, VERB, PUNCT]","[(кухнята, 0.7071067811865475), (мирише, 0.707...",0.385488,"[-0.05895353, 0.02678768, 0.011074896, 0.03241...","[0.45568153, -0.027227957, 0.09161861, -0.1835..."
1,0,1,0,Ordinary Life,commissive,no emotion,I'll throw out the garbage .,Ще изхвърля боклука.,"[AUX, VERB, NOUN, PUNCT]","[(боклука, 0.6060433187339399), (изхвърля, 0.6...",-0.184246,"[-0.05321903, 0.008844021, 0.07036609, 0.04865...","[0.2159934, -0.034524005, 0.06626176, 0.208314..."
2,1,0,0,Ordinary Life,directive,happiness,"So Dick , how about getting some coffee for to...","Така че Dick , какво ще кажете за получаване н...","[ADV, SCONJ, PROPN, PUNCT, DET, AUX, VERB, ADP...","[(dick, 0.2693740845690302), (вечер, 0.2693740...",-0.122162,"[-0.0032325375, -0.014675511, 0.024256792, 0.0...","[0.47156695, -0.14618982, -0.044646528, -0.045..."
3,1,1,0,Ordinary Life,commissive,disgust,Coffee ?,Кафе ?,"[NOUN, PUNCT]","[(кафе, 1.0)]",-0.163817,"[0.0019401921, 0.03712749, 0.025385574, 0.0153...","[0.6692529, -0.5150005, 0.54632986, -0.2239101..."
4,1,1,1,Ordinary Life,commissive,disgust,I don ’ t honestly like that kind of stuff .,"Честно казано, не харесвам такива неща.","[ADV, ADJ, PUNCT, PART, VERB, DET, DET, PUNCT]","[(казано, 0.42435658024974), (не, 0.3156065018...",-0.176561,"[0.00017724124, -0.039979186, 0.014543567, 0.0...","[0.5595237, -0.0887767, -0.089905106, 0.080638..."
5,1,2,0,Ordinary Life,directive,no emotion,"Come on , you can at least try a little , besi...","Хайде , можеш поне да опиташ малко , освен циг...","[PART, PUNCT, VERB, ADV, AUX, VERB, ADV, PUNCT...","[(да, 0.34410595277587486), (малко, 0.29252149...",0.024798,"[0.021950508, -0.041999117, 0.0140455365, 0.01...","[0.46075618, -0.087264046, -0.12859842, -0.088..."
6,1,3,0,Ordinary Life,inform,anger,What ’ s wrong with that ?,Какво не е наред с това?,"[DET, PART, AUX, ADV, ADP, PRON, PUNCT]","[(какво, 0.46968603824569793), (наред, 0.55251...",-0.198530,"[-0.00087265484, -0.02994658, 0.005080737, 0.0...","[0.4478457, -0.19270393, -0.08149754, -0.12825..."
7,1,3,1,Ordinary Life,inform,anger,Cigarette is the thing I go crazy for .,"Цигарата е нещото, по което полудявам.","[NOUN, AUX, NOUN, PUNCT, ADP, PRON, VERB, PUNCT]","[(което, 0.4601578921271882), (нещото, 0.46015...",-0.239203,"[0.022024015, -0.015521896, -0.003359329, 0.00...","[0.57746446, -0.017069545, 0.03995408, -0.0177..."
8,1,4,0,Ordinary Life,inform,no emotion,"Not for me , Dick .","Не и за мен, Дик.","[PART, CCONJ, ADP, PRON, PUNCT, PROPN, PUNCT]","[(дик, 0.5525124243793842), (за, 0.46968603824...",-0.075781,"[-0.018605703, -0.014853599, -0.021822492, 0.0...","[0.54453075, -0.071342036, 0.0049987193, 0.049..."
9,2,0,0,Ordinary Life,question,no emotion,Are things still going badly with your housegu...,Все още ли нещата с вашия съквартирант вървят ...,"[ADV, ADV, PART, PRON, ADP, DET, NOUN, VERB, A...","[(вашия, 0.35355339059327373), (все, 0.3535533...",-0.287767,"[-0.018371671, -0.009949706, -0.030019002, 0.0...","[0.24767524, -0.0904341, 0.043866098, 0.049756..."

In [ ]:
import logging
from gensim.models import Word2Vec
from gensim.models.word2vec import LineSentence

# --- Configuration ---
# Set up logging to monitor the training process of the Word2Vec models.
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

# --- Function Definition ---
def evaluate_word2vec_model(model, evaluation_dict, topn=30):
    """
    Evaluates the semantic similarity performance of a trained Word2Vec model.

    The function assesses the model by checking if a predefined list of semantically
    similar words for a given headword is present in the top 'n' most similar
    words predicted by the model.

    Args:
        model (gensim.models.Word2Vec): The trained Word2Vec model instance.
        evaluation_dict (dict): A dictionary where each key is a headword and its
                                value is a list of words expected to be similar.
        topn (int): The number of most similar words to retrieve from the model
                    for comparison.

    Returns:
        int: The total score, calculated as the cumulative number of successful
             matches found across all headwords in the evaluation dictionary.
    """
    total_score = 0
    print("\n--- Starting Model Evaluation ---")

    for head_word, expected_similar_words in evaluation_dict.items():
        # Verify that the headword exists in the model's vocabulary.
        if head_word not in model.wv:
            print(f"Warning: Headword '{head_word}' not found in model vocabulary. Skipping.")
            continue

        try:
            # Retrieve the top N most similar words predicted by the model.
            predicted_similar_words = [word for word, score in model.wv.most_similar(head_word, topn=topn)]

            # Identify the intersection between the expected and predicted lists.
            matches = set(expected_similar_words) & set(predicted_similar_words)

            # Calculate the score for the current headword.
            score = len(matches)
            total_score += score

            print(f"Headword '{head_word}': Found {score}/{len(expected_similar_words)} matches. "
                  f"Examples: {list(matches)[:5]}")

        except Exception as e:
            print(f"An error occurred while processing '{head_word}': {e}")

    print("--- Evaluation Complete ---")
    return total_score

# --- Main Execution Block ---

# 1. Corpus and Data Preparation
# Specify the path to the pre-processed text corpus.
# The corpus should be a single text file where each line constitutes a sentence.
corpus_file = 'bulgarian_corpus.txt'
sentences = LineSentence(corpus_file)

# 2. Hyperparameter Configuration
# Define a list of hyperparameter combinations to train and evaluate.
# 'sg=1' corresponds to the Skip-gram algorithm.
# 'sg=0' corresponds to the Continuous Bag-of-Words (CBOW) algorithm.
param_combinations = [
    # Skip-gram Models
    {'vector_size': 150, 'window': 5, 'sg': 1, 'min_count': 5},
    {'vector_size': 300, 'window': 5, 'sg': 1, 'min_count': 5},
    {'vector_size': 300, 'window': 10, 'sg': 1, 'min_count': 5},
    {'vector_size': 300, 'window': 5, 'sg': 1, 'min_count': 10},
    # CBOW Models
    {'vector_size': 150, 'window': 5, 'sg': 0, 'min_count': 5},
    {'vector_size': 300, 'window': 10, 'sg': 0, 'min_count': 5},
]

# 3. Evaluation Set Definition
# A custom dictionary to test the model's understanding of semantic similarity
# for a curated set of Bulgarian words.
bulgarian_test_words = {
    # Nouns
    'цар': ['крал', 'император', 'монарх', 'владетел', 'принц', 'престолонаследник', 'княз'],
    'град': ['столица', 'селище', 'квартал', 'местност', 'градче', 'мегаполис', 'община', 'населено_място'],
    'жена': ['съпруга', 'дама', 'майка', 'момиче', 'госпожа', 'млада_жена', 'девойка', 'матрона'],
    'кола': ['автомобил', 'превозно_средство', 'машина', 'камион', 'бус', 'колесар', 'мотор'],
    'учител': ['преподавател', 'педагог', 'наставник', 'ментор', 'образовател', 'лектор', 'треньор'],
    'ученик': ['студент', 'школник', 'учещ', 'курсист', 'стажант', 'абитуриент', 'възпитаник'],
    'книга': ['роман', 'повест', 'разказ', 'том', 'литература', 'четиво', 'издание', 'електронна_книга'],
    'информация': ['данни', 'сведения', 'факти', 'знание', 'известия', 'новини', 'съобщения', 'справка', 'справки'],
    'пътуване': ['обиколка', 'екскурзия', 'турне', 'пътешествие', 'посещение', 'почивка', 'обиколен_маршрут', 'транзит'],
    'свобода': ['независимост', 'автономия', 'воля', 'непринуденост', 'либерализъм', 'освобождение', 'революция'],
    'щастие': ['радост', 'веселие', 'доволство', 'благополучие', 'блаженство', 'удоволствие', 'наслада'],
    'природа': ['околна_среда', 'естество', 'флора', 'фауна', 'пейзаж', 'ландшафт', 'жива_природа'],
    # Adjectives
    'красив': ['хубав', 'прекрасен', 'очарователен', 'симпатичен', 'привлекателен', 'ослепителен', 'изящен', 'елегантен'],
    'голям': ['огромен', 'масивен', 'обемист', 'внушителен', 'колосален', 'гигантски', 'монументален', 'широк'],
    'малък': ['дребен', 'миниатюрен', 'ситен', 'компактен', 'нищожен', 'незначителен', 'кратък'],
    'добър': ['мил', 'почтен', 'честен', 'справедлив', 'качествен', 'приятен', 'успешен', 'достоен', 'отличен'],
    'тъжен': ['нещастен', 'печален', 'мрачен', 'депресиран', 'угнетен', 'отчаян', 'потиснат', 'самотен'],
    # Verbs
    'говоря': ['казвам', 'разговарям', 'приказвам', 'беседвам', 'шепна', 'рецитирам', 'изказвам_се', 'разказвам'],
    'правя': ['извършвам', 'създавам', 'изработвам', 'осъществявам', 'изпълнявам', 'построявам'],
    'отивам': ['тръгвам', 'заминавам', 'пътувам', 'ходя', 'пристигам', 'отида', 'придвижвам_се', 'отправям_се'],
    'мисля': ['размишлявам', 'разсъждавам', 'обмислям', 'умувам', 'преценявам', 'преосмислям', 'смятам', 'считам'],
}

# 4. Model Training and Selection Loop
best_score = -1
best_params = None
best_model = None

for i, params in enumerate(param_combinations, 1):
    print(f"\n--- Training Model {i}/{len(param_combinations)} ---")
    print(f"Parameters: {params}")

    # Initialize and train the Word2Vec model.
    model = Word2Vec(
        sentences=sentences,
        vector_size=params['vector_size'],
        window=params['window'],
        min_count=params['min_count'],
        sg=params['sg'],
        workers=4  # Specify the number of CPU cores for parallelization.
    )

    # Evaluate the newly trained model.
    current_score = evaluate_word2vec_model(model, bulgarian_test_words, topn=30)
    print(f"Result: Model {i} achieved a score of {current_score}.")

    # Update the best model if the current one performs better.
    if current_score > best_score:
        best_score = current_score
        best_params = params
        best_model = model
        print(f"Update: New best model identified with score {best_score}.")

# 5. Save the Best Performing Model
if best_model:
    model_save_path = "best_bulgarian_word2vec.model"
    best_model.save(model_save_path)
    print("\n--- Final Result ---")
    print(f"The best performing model achieved a score of {best_score}.")
    print(f"Optimal parameters: {best_params}")
    print(f"Model saved to file: '{model_save_path}'")
else:
    print("\nTraining process concluded, but no models were successfully trained or evaluated.")

The best model achieved a score of 41 with parameters: {'vector_size': 150, 'window': 5, 'sg': 0, 'min_count': 5}

sg:0
It was more efficient at the end, since its faster and requires less data. Assumptions were made that we have a big enough dataset which was not the case. It learns to predict a word from its surrounding context. It works better on a smaller dataset.

Vector_size:150
This choice balances computational efficiency with model capacity. Lower-dimensional vectors (150) require less memory and training time compared to higher dimensions like 300. 300+ leads to overfitting due to the size of the dataset. The smaller vector size better captures the features presented in the data.

Min_count: 5
It is a standard choice in the industry since min_count=5 filters out very rare words that would have poor vector representations due to insufficient training examples, while preserving enough vocabulary for good coverage.

Epochs: The gensim library, by default, trains for 5 epochs. 1 epoch is mostly never enough. It could be compared to reading a book once. On the second you look for connections and usually on the 4/5th time you can make a proper analysis. More epochs might lead to overfitting

### Testing and Comparing Both Models

In [16]:
from gensim.models import Word2Vec

model = Word2Vec.load("bulgarian_wiki_word2vec.model")

# Find the 10 most similar words to "България" (Bulgaria)
try:
    similar_words = model.wv.most_similar('българия', topn=10)
    print("Words similar to 'България':")
    for word, score in similar_words:
        print(f"- {word}: {score:.4f}")
except KeyError:
    print("The word 'българия' is not in the model's vocabulary. Try another common word.")

# Find the 10 most similar words to "цар" (tsar/king)
try:
    similar_words = model.wv.most_similar('цар', topn=10)
    print("\nWords similar to 'цар':")
    for word, score in similar_words:
        print(f"- {word}: {score:.4f}")
except KeyError:
    print("The word 'цар' is not in the model's vocabulary. Try another common word.")

2025-09-18 15:38:10,294 : INFO : loading Word2Vec object from bulgarian_wiki_word2vec.model
2025-09-18 15:38:10,559 : INFO : loading wv recursively from bulgarian_wiki_word2vec.model.wv.* with mmap=None
2025-09-18 15:38:10,560 : INFO : loading vectors from bulgarian_wiki_word2vec.model.wv.vectors.npy with mmap=None
2025-09-18 15:38:10,614 : INFO : loading syn1neg from bulgarian_wiki_word2vec.model.syn1neg.npy with mmap=None
2025-09-18 15:38:10,671 : INFO : setting ignored attribute cum_table to None
2025-09-18 15:38:12,315 : INFO : Word2Vec lifecycle event {'fname': 'bulgarian_wiki_word2vec.model', 'datetime': '2025-09-18T15:38:12.314440', 'gensim': '4.3.3', 'python': '3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]', 'platform': 'Windows-10-10.0.26100-SP0', 'event': 'loaded'}

Words similar to 'България':
- асеновград: 0.5866
- бълария: 0.5834
- софия: 0.5771
- горянско: 0.5721
- русофилство: 0.5709
- пловдив: 0.5703
- потв: 0.5646
- кюстендил: 0.5585
- нуртс: 0.5582
- утрешна: 0.5576

Words similar to 'цар':
- царица: 0.7548
- царят: 0.7548
- царя: 0.7471
- царете: 0.7053
- касандър: 0.6790
- обединител: 0.6733
- сенекерим: 0.6711
- лидийския: 0.6711
- хасмонейския: 0.6650
- гигес: 0.6531

In [18]:
from gensim.models import KeyedVectors, Word2Vec

# Load both models
ft_model = load_facebook_model('cc.bg.300.bin')

custom_model_path = "bulgarian_wiki_word2vec.model"

custom_model = Word2Vec.load(custom_model_path).wv


# Define Words to Test
words_to_test = ['жена', 'пич', 'полицай']

# Comparison
for word in words_to_test:
    print(f"\n--- Comparing results for the word: '{word}' ---")

    try:
        print("\nPretrained FastText Results:")
        ft_similar = ft_model.wv.most_similar(word, topn=7)
        for term, score in ft_similar:
            print(f"- {term}: {score:.4f}")
    except KeyError:
        print(f"'{word}' not found in the FastText model.")

    try:
        print("\nCustom Word2Vec Results:")
        custom_similar = custom_model.most_similar(word, topn=7)
        for term, score in custom_similar:
            print(f"- {term}: {score:.4f}")
    except KeyError:
        print(f"'{word}' not found in the custom model.")

2025-09-18 15:46:55,906 : INFO : loading 2000000 words for fastText model from cc.bg.300.bin

MemoryError: Unable to allocate 4.47 GiB for an array with shape (1200000000,) and data type float32

In [19]:
import pandas as pd
import numpy as np
from gensim.models import KeyedVectors, Word2Vec
import re
import pickle

# Load FastText model
ft_model = load_facebook_model('cc.bg.300.bin')

# Load Custom Word2Vec model
custom_model = Word2Vec.load("bulgarian_wiki_word2vec.model")
print("Custom model loaded.")

df = pd.read_csv("bg_final.csv")
text_column = 'sentence_text_bg'
print(f"Dataset 'bg_final.csv' loaded with {len(df)} rows.")

# Function to convert sentences to vectors
def sentence_to_vector(sentence, model):
    """
    Converts a sentence string into a vector by averaging its word vectors.
    Returns a zero vector if no words are found in the model's vocabulary.
    """
    words = re.findall(r'\b\w+\b', str(sentence).lower())

    word_vectors_source = model.wv if hasattr(model, 'wv') else model

    vector_size = word_vectors_source.vector_size
    word_vectors = []

    for word in words:
        if word in word_vectors_source:
            word_vectors.append(word_vectors_source[word])

    if not word_vectors:
        return np.zeros(vector_size, dtype=np.float32)

    return np.mean(word_vectors, axis=0)

# Generate sentence vectors for the FastText model
df['sentence_vector_fasttext'] = df[text_column].apply(
    lambda s: sentence_to_vector(s, ft_model)
)

# Generate sentence vectors for the Custom model
df['sentence_vector_custom'] = df[text_column].apply(
    lambda s: sentence_to_vector(s, custom_model)
)
print("Custom model vectors created.")

# Save the DataFrame with new features to a pickle file
output_path = 'bg_features.pkl'
with open(output_path, 'wb') as f:
    pickle.dump(df, f)

print(f"Your new DataFrame with vector features has been saved to: {output_path}")

print("\nSample of the final DataFrame:")
print(df[['sentence_text_bg', 'sentence_vector_custom', 'sentence_vector_fasttext']].head())

2025-09-18 15:47:45,071 : INFO : loading 2000000 words for fastText model from cc.bg.300.bin

MemoryError: Unable to allocate 4.47 GiB for an array with shape (1200000000,) and data type float32

## Subtask 6: Additional Feature

In [20]:
# 1. Word Count: The total number of words in the sentence.
df['word_count'] = df['sentence_text_bg'].apply(lambda x: len(str(x).split()))

# 2. Exclamation Mark Count: A strong signal for high-arousal emotions.
df['exclamation_marks'] = df['sentence_text_bg'].str.count('!')

# 3. Question Mark Count: Can signal surprise, confusion, or anger.
df['question_marks'] = df['sentence_text_bg'].str.count('\?')

# 4. Uppercase Word Count: A proxy for "shouting" in text.
df['uppercase_words'] = df['sentence_text_bg'].apply(
    lambda x: sum(1 for word in str(x).split() if word.isupper() and len(word) > 1)
)
df.head(10)

,dialogue_id,utterance_id,sentence_id,topic,dialog_act,emotion,sentence_text,sentence_text_bg,POS_Tags,TF-IDF,Sentiment_Score,Pretrained_Embeddings,Custom_Embeddings,word_count,exclamation_marks,question_marks,uppercase_words
0,0,0,0,Ordinary Life,directive,disgust,The kitchen stinks .,Кухнята мирише.,"[NOUN, VERB, PUNCT]","[(кухнята, 0.7071067811865475), (мирише, 0.707...",0.385488,"[-0.05895353, 0.02678768, 0.011074896, 0.03241...","[0.45568153, -0.027227957, 0.09161861, -0.1835...",2,0,0,0
1,0,1,0,Ordinary Life,commissive,no emotion,I'll throw out the garbage .,Ще изхвърля боклука.,"[AUX, VERB, NOUN, PUNCT]","[(боклука, 0.6060433187339399), (изхвърля, 0.6...",-0.184246,"[-0.05321903, 0.008844021, 0.07036609, 0.04865...","[0.2159934, -0.034524005, 0.06626176, 0.208314...",3,0,0,0
2,1,0,0,Ordinary Life,directive,happiness,"So Dick , how about getting some coffee for to...","Така че Dick , какво ще кажете за получаване н...","[ADV, SCONJ, PROPN, PUNCT, DET, AUX, VERB, ADP...","[(dick, 0.2693740845690302), (вечер, 0.2693740...",-0.122162,"[-0.0032325375, -0.014675511, 0.024256792, 0.0...","[0.47156695, -0.14618982, -0.044646528, -0.045...",15,0,1,0
3,1,1,0,Ordinary Life,commissive,disgust,Coffee ?,Кафе ?,"[NOUN, PUNCT]","[(кафе, 1.0)]",-0.163817,"[0.0019401921, 0.03712749, 0.025385574, 0.0153...","[0.6692529, -0.5150005, 0.54632986, -0.2239101...",2,0,1,0
4,1,1,1,Ordinary Life,commissive,disgust,I don ’ t honestly like that kind of stuff .,"Честно казано, не харесвам такива неща.","[ADV, ADJ, PUNCT, PART, VERB, DET, DET, PUNCT]","[(казано, 0.42435658024974), (не, 0.3156065018...",-0.176561,"[0.00017724124, -0.039979186, 0.014543567, 0.0...","[0.5595237, -0.0887767, -0.089905106, 0.080638...",6,0,0,0
5,1,2,0,Ordinary Life,directive,no emotion,"Come on , you can at least try a little , besi...","Хайде , можеш поне да опиташ малко , освен циг...","[PART, PUNCT, VERB, ADV, AUX, VERB, ADV, PUNCT...","[(да, 0.34410595277587486), (малко, 0.29252149...",0.024798,"[0.021950508, -0.041999117, 0.0140455365, 0.01...","[0.46075618, -0.087264046, -0.12859842, -0.088...",12,0,0,0
6,1,3,0,Ordinary Life,inform,anger,What ’ s wrong with that ?,Какво не е наред с това?,"[DET, PART, AUX, ADV, ADP, PRON, PUNCT]","[(какво, 0.46968603824569793), (наред, 0.55251...",-0.198530,"[-0.00087265484, -0.02994658, 0.005080737, 0.0...","[0.4478457, -0.19270393, -0.08149754, -0.12825...",6,0,1,0
7,1,3,1,Ordinary Life,inform,anger,Cigarette is the thing I go crazy for .,"Цигарата е нещото, по което полудявам.","[NOUN, AUX, NOUN, PUNCT, ADP, PRON, VERB, PUNCT]","[(което, 0.4601578921271882), (нещото, 0.46015...",-0.239203,"[0.022024015, -0.015521896, -0.003359329, 0.00...","[0.57746446, -0.017069545, 0.03995408, -0.0177...",6,0,0,0
8,1,4,0,Ordinary Life,inform,no emotion,"Not for me , Dick .","Не и за мен, Дик.","[PART, CCONJ, ADP, PRON, PUNCT, PROPN, PUNCT]","[(дик, 0.5525124243793842), (за, 0.46968603824...",-0.075781,"[-0.018605703, -0.014853599, -0.021822492, 0.0...","[0.54453075, -0.071342036, 0.0049987193, 0.049...",5,0,0,0
9,2,0,0,Ordinary Life,question,no emotion,Are things still going badly with your housegu...,Все още ли нещата с вашия съквартирант вървят ...,"[ADV, ADV, PART, PRON, ADP, DET, NOUN, VERB, A...","[(вашия, 0.35355339059327373), (все, 0.3535533...",-0.287767,"[-0.018371671, -0.009949706, -0.030019002, 0.0...","[0.24767524, -0.0904341, 0.043866098, 0.049756...",9,0,1,0

In [22]:
# Keep only the required columns
final_features = df[['sentence_text', 'sentence_text_bg', 'POS_Tags', 'TF-IDF', 'Sentiment_Score', 'Pretrained_Embeddings', 'Custom_Embeddings', 'word_count', 'exclamation_marks', 'question_marks', 'uppercase_words']]

# Save the first 10 rows as required deliverable
final_features.head(10).to_csv("NLP_features.csv", sep="\t", index=False)